INSERT INTO TPP_DOC_TYPE VALUES (1, 'CRM');
INSERT INTO TPP_DOC_TYPE VALUES (2, 'FAKTURA');
INSERT INTO TPP_DOC_TYPE VALUES (3, 'DDPP');
INSERT INTO TPP_DOC_TYPE VALUES (4, 'UPOMÍNKA');

INSERT INTO TPP_STATUS_TYPE VALUES (1, 'Data došla');
INSERT INTO TPP_STATUS_TYPE VALUES (2, 'Zformátováno');
INSERT INTO TPP_STATUS_TYPE VALUES (3, 'Uloženo v DB');
INSERT INTO TPP_STATUS_TYPE VALUES (4, 'Vytištìno');
INSERT INTO TPP_STATUS_TYPE VALUES (5, 'Zaobálkováno');
INSERT INTO TPP_STATUS_TYPE VALUES (6, 'Ofrankováno');
INSERT INTO TPP_STATUS_TYPE VALUES (7, 'Pøedáno odesilateli');

INSERT INTO TPP_DIST_CHANNEL VALUES (1, 'Tisk');
INSERT INTO TPP_DIST_CHANNEL VALUES (2, 'Elektronicky');
INSERT INTO TPP_DIST_CHANNEL VALUES (3, 'Vlastní roznos');
INSERT INTO TPP_DIST_CHANNEL VALUES (4, 'B2B');
INSERT INTO TPP_DIST_CHANNEL VALUES (5, 'B2C');
INSERT INTO TPP_DIST_CHANNEL VALUES (6, 'ELFA');

INSERT INTO TPP_ROLE VALUES ('admin');
INSERT INTO TPP_ROLE VALUES ('operator');
INSERT INTO TPP_ROLE VALUES ('viewer');


INSERT INTO TPP_OPERATOR (ID,NAME) VALUES (1, 'CPOST');
INSERT INTO TPP_OPERATOR (ID,NAME) VALUES (2, 'MDS');
INSERT INTO TPP_OPERATOR (ID,NAME) VALUES (3, 'ELE');


INSERT INTO TPP_USER ([USERNAME], [PASSWORD], [ROLE]) VALUES ('admin',' $v3.dy73f6hI',1);
insert into tpp_user ([username],[password],[role]) values ('operator', '$2a$07$u8hfouwm3hdftsm3gp4aeuRcsIs8n4r4C4cWDsfithCCPoaso4Uzq',2);
insert into tpp_user ([username],[password],[role]) values ('guest', '$2a$07$p4e5x3cp1mmn9kkfbv5caul7Q70pCFrSopWS48DIfHvXoXhVIH6ku',3);